INSERT INTO locais (nome, endereco) VALUES
('Karina Sampaio', 'Rio de Janeiro, Brasil'),
('Izabel Sampaio', 'Rio de Janeiro, Brasil'),
('Beyonce Knowles', 'Texas, EUA'),
('Taylor Swift', 'Nova York, EUA'),
('Lucas Montes', 'Recife, Brasil'),
('Ana Júlia', 'São Paulo, Brasil'),
('Carlos Eduardo', 'Belo Horizonte, Brasil'),
('João Silva', 'Rio de Janeiro, Brasil'),
('Maria Oliveira', 'São Paulo, Brasil'),
('Pedro Santos', 'Belo Horizonte, Brasil'),
('Ana Souza', 'Salvador, Brasil'),
('Carlos Ferreira', 'Porto Alegre, Brasil'),
('Fernanda Lima', 'Brasília, Brasil'),
('Rafaela Mendes', 'Curitiba, Brasil'),
('Lucas Rodrigues', 'Fortaleza, Brasil'),
('Patrícia Almeida', 'Recife, Brasil'),
('Rodrigo Costa', 'Manaus, Brasil'),
('Juliana Pereira', 'Rio de Janeiro, Brasil'),
('Gustavo Silva', 'São Paulo, Brasil'),
('Mariana Oliveira', 'Belo Horizonte, Brasil'),
('Ricardo Santos', 'Salvador, Brasil'),
('Amanda Souza', 'Porto Alegre, Brasil'),
('Diego Ferreira', 'Brasília, Brasil'),
('Carla Lima', 'Curitiba, Brasil'),
('Fabiana Mendes', 'Fortaleza, Brasil'),
('Paulo Rodrigues', 'Recife, Brasil'),
('Camila Almeida', 'Manaus, Brasil'),
('Luciana Costa', 'Rio de Janeiro, Brasil'),
('Fábio Pereira', 'São Paulo, Brasil'),
('Vanessa Silva', 'Belo Horizonte, Brasil'),
('Daniel Oliveira', 'Salvador, Brasil'),
('Tatiane Santos', 'Porto Alegre, Brasil'),
('Marcos Souza', 'Brasília, Brasil'),
('Luiza Ferreira', 'Curitiba, Brasil'),
('André Lima', 'Fortaleza, Brasil'),
('Renata Mendes', 'Recife, Brasil'),
('Thiago Rodrigues', 'Manaus, Brasil'),
('Bianca Almeida', 'Rio de Janeiro, Brasil'),
('Roberto Costa', 'São Paulo, Brasil'),
('Natália Pereira', 'Belo Horizonte, Brasil'),
('Lucas Silva', 'Salvador, Brasil'),
('Caroline Oliveira', 'Porto Alegre, Brasil'),
('Bruno Santos', 'Brasília, Brasil'),
('Mariana Souza', 'Curitiba, Brasil'),
('Pedro Ferreira', 'Fortaleza, Brasil'),
('Ana Lima', 'Recife, Brasil'),
('Guilherme Mendes', 'Manaus, Brasil'),
('Isabela Rodrigues', 'Rio de Janeiro, Brasil'),
('Felipe Almeida', 'São Paulo, Brasil'),
('Larissa Costa', 'Belo Horizonte, Brasil'),
('Gabriel Pereira', 'Salvador, Brasil'),
('Beatriz Silva', 'Porto Alegre, Brasil');